[phases.setup]
nixPkgs = ["nodejs_20", "corepack"]

[phases.install]
cmds = ["corepack enable", "corepack pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["corepack pnpm run build"]

[start]
cmd = "corepack pnpm start"

